import cveFieldPaths from "@/generated/schemas/cve-5.2.0/field-paths.json";

/*
 * A single static catalog (the base CVE 5.2.0 profile) regardless of
 * which profile the current record actually uses — the Templates
 * section isn't otherwise profile-aware, and GCVE only adds an
 * `x_gcve` extension on top of the same CVE shape, so this still
 * covers the vast majority of useful suggestions. Worst case for a
 * GCVE-only field: no suggestion offered, same as today — typing
 * the path by hand always still works.
 */

export interface PathSuggestion {
  path: string;
  title: string | null;
}

interface RawFieldPath {
  path: string;
  title: string | null;
  type: string;
}

/*
 * field-paths.json (generated by scripts/generate_editor_schemas.py)
 * marks every array segment with a literal "[]" — it only records
 * an array's element shape once, not per index — turned into a
 * concrete ".0." here since that's what setPath()/
 * applyTemplateFields() need to actually address a value. Every
 * suggestion defaults array indices to 0; editing that digit for a
 * different array position is left to the user.
 */
function toConcretePath(
  path: string,
): string {
  return path.replace(/\[]/g, ".0");
}

const CATALOG: PathSuggestion[] = (cveFieldPaths as RawFieldPath[]).map(
  (field) => ({
    path: toConcretePath(field.path),
    title: field.title,
  }),
);

/**
 * Ranks exact-prefix matches first, then any other substring match
 * on the path or title, capped at `limit` so a broad query (e.g. a
 * single common letter) doesn't dump the whole catalog into the
 * dropdown.
 */
export function suggestPaths(
  query: string,
  limit = 20,
): PathSuggestion[] {
  const term = query.trim().toLowerCase();

  if (!term) {
    return [];
  }

  const startsWith: PathSuggestion[] = [];
  const contains: PathSuggestion[] = [];

  for (const entry of CATALOG) {
    if (entry.path.toLowerCase().startsWith(term)) {
      startsWith.push(entry);
    } else if (
      entry.path.toLowerCase().includes(term)
      || entry.title?.toLowerCase().includes(term)
    ) {
      contains.push(entry);
    }
  }

  return [...startsWith, ...contains].slice(0, limit);
}
