"""add user is_admin and is_active

Revision ID: 24d4fde82b6f
Revises: 536cd274f256
Create Date: 2026-09-14 14:26:39.450418

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '24d4fde82b6f'
down_revision = '536cd274f256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (nullable=False otherwise
    # fails against the users that already exist) — dropped again below
    # since the Python-level default= on the model only applies to new
    # inserts, not this column-add.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin', server_default=None)
        batch_op.alter_column('is_active', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
