"""add user cna credential table

Revision ID: 536cd274f256
Revises: 90fe9d2a650f
Create Date: 2026-09-14 11:55:11.102036

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '536cd274f256'
down_revision = '90fe9d2a650f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cna_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('cve_url', sa.String(length=512), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.Column('org_id', sa.String(length=256), nullable=False),
    sa.Column('cve_api_org', sa.String(length=256), nullable=False),
    sa.Column('cve_api_user', sa.String(length=256), nullable=False),
    sa.Column('cve_api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target', name='uq_user_cna_credential_user_target')
    )
    with op.batch_alter_table('user_cna_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_cna_credential_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cna_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_cna_credential_user_id'))

    op.drop_table('user_cna_credential')
    # ### end Alembic commands ###
