"""Add CNA publication table

Revision ID: 5e748ccf2cb0
Revises: be968eac06ef
Create Date: 2026-08-31 13:10:55.658390

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5e748ccf2cb0'
down_revision = 'be968eac06ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cna_publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_identifier', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cve_id', sa.String(length=64), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_request', sa.Text(), nullable=True),
    sa.Column('last_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_identifier', 'target', name='uq_cna_publication_record_target')
    )
    with op.batch_alter_table('cna_publication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cna_publication_record_identifier'), ['record_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cna_publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cna_publication_record_identifier'))

    op.drop_table('cna_publication')
    # ### end Alembic commands ###
