"""add user table

Revision ID: 90fe9d2a650f
Revises: 5e748ccf2cb0
Create Date: 2026-09-14 11:47:58.875833

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90fe9d2a650f'
down_revision = '5e748ccf2cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_template_created_by_id_user', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('vulnerability_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vulnerability_record_created_by_id_user', 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vulnerability_record_created_by_id_user', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_template_created_by_id_user', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
